spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: APPMIC-E-CommercePlugins-maintenance
            uri: lb://APPMIC-E-CommercePlugins-maintenance
            predicates:
              - Path=/maintenance/**
            filters:
              - StripPrefix=1
          - id: APPMIC-E-CommercePlugins-orders
            uri: lb://APPMIC-E-CommercePlugins-orders
            predicates:
              - Path=/orders/**
            filters:
              - StripPrefix=1