spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: APPMIC-E-CommercePlugins-maintenance
            uri: lb://APPMIC-E-CommercePlugins-maintenance
            predicates:
              - Path=/api/maintenance/**
            filters:
              - StripPrefix=2
          - id: APPMIC-E-CommercePlugins-orders
            uri: lb://APPMIC-E-CommercePlugins-orders
            predicates:
              - Path=/api/maintenance/**
            filters:
              - StripPrefix=2